openapi: 3.0.0
info:
  title: OpenAPI спецификация example_trello
  version: 0.0.1
servers:
  - url: http://localhost:8080/api/
    description: Dev server  
  
paths:
  /register:
    post:
      summary: Метод регистрации пользователя в системе
      description: Метод предназначен для сохранения в БД данных по новому пользователю.
      operationId: createUser
      tags:
        - Auth
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreateUser"
      responses:
        '200':
          description: Подтверждение успешного сохранения
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CreateUser"
        '400':
          "description": Некорректные входные данные. Возвращает список атрибутов с ошибками
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
        default:
          description: Любая неожиданная ошибка
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  /login:
    post:
      summary: Метод авторизации пользователя в системе
      description: Метод предназначен для авторизации и входа в систему пользователя.
      operationId: loginUser
      tags:
        - Auth
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/LoginUser"
      responses:
        '200':
          description: Подтверждение успешного входа в систему
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
        '400':
          description: Некорректное входные данные. Возвращает список атрибутов с ошибками
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
        default:
          description: Любая неожиданная ошибка
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  /logout:
    post:
      summary: Метод выхода пользователя из системы
      description: Метод предназначен для удаления сессии из браузера пользователя
      operationId: logoutUser
      tags:
        - Auth
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/LoginUser"
      responses:
        '200':
          description: Подтверждение успешного выхода из системы
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
        default:
          description: Любая неожиданная ситуация
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  /forgot_password:
    post:
      summary: Метод отправляет пин-код на почту пользователя, для идентификации.
      description: Метод предназначен для отправки специального кода для подтверждения принадлежности пользователя и текущего аккаунта
      operationId: forgotPassword
      tags:
        - Reset Password
      requestBody:
        required: true
        content:
          'application/json':
            schema:
              $ref: "#/components/schemas/ForgotPassword"
      responses:
        '200':
          "description": Подтверждение успешной отправки
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ForgotPassword"
        '400':
          "description": Некорректные входные данные. Возвращает список атрибутов с ошибками
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
        default:
          description: Любая неожиданная ошибка
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  /send_pincode:
    post:
      summary: Метод отправляет введенный пин-код пользователем на сервер.
      description: Метод предназначен для подтверждения личности данного пользователя и сопровождения на финальный этап сброса пароля
      operationId: sendPincode
      tags:
        - Reset Password
      requestBody:
        required: true
        content:
          'application/json':
            schema:
              $ref: "#/components/schemas/SendPincode"
      responses:
        '200':
          "description": Подтверждение успешной отправки
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SendPincode"
        '400':
          "description": Некорректные входные данные. Возвращает список атрибутов с ошибками
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
        default:
          description: Любая неожиданная ошибка
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  /reset_password:
    post:
      summary: Метод отправляет пароль и пароль-подтверждение на сервер.
      description: Метод предназначен для перезаписи старого пароля на новый.
      operationId: resetPassword
      tags:
        - Reset Password
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ResetPassword"
      responses:
        '200':
          description: Подтверждение смены пароля
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ResetPassword"
        '400':
          description: Некорректные входные данные. Возвращает список атрибутов с ошибками
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
        default:
          description: Любая неожиданная ошибка
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"


  /organizations:
    get:
      summary: Метод получения организаций
      description: Метод предназначен для получения списка всех организаций, сохраненных в БД.
      operationId: getOrganizations
      tags:
        - Organizations
      responses:
        '200':
          "description": Список организаций
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Organizations"
        default:
          description: Любая неожиданная ошибка
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
    post:
      summary: Метод добавления организации
      description: Метод предназначен для сохранения в БД данных по новой организации.
      operationId: createOrganization
      tags:
        - Organizations
      requestBody:
        required: true
        content:
          'application/json':
            schema:
              $ref: "#/components/schemas/Organization"
      responses:
        '200':
          "description": Подтверждение успешного сохранения
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Organization"
        '400':
          "description": Некорректные входные данные. Возвращает список атрибутов с ошибками
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
        default:
          description: Любая неожиданная ошибка
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
                
  /organizations/{id}:
    get:
      summary: Метод получения организации по идентификатору
      operationId: getOrganizationById
      tags:
        - Organizations
      parameters:
        - name: id
          in: path
          required: true
          description: Идентификатор организации
          schema:
            type: string
      responses:
        '200':
          "description": Организация
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Organization"
        default:
          description: Любая неожиданная ошибка
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
    put:
      summary: Метод обновления организации
      description: Метод предназначен для обновления в БД данных по имеющейся организации.
      operationId: updateOrganization
      tags:
        - Organizations
      parameters:
        - name: id
          in: path
          required: true
          description: Идентификатор организации
          schema:
            type: string
      requestBody:
        required: true
        content:
          'application/json':
            schema:
              $ref: "#/components/schemas/Organization"
      responses:
        '200':
          "description": Подтверждение успешного обновления
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Organization"
        '400':
          "description": Некорректные входные данные. Возвращает список атрибутов с ошибками
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
        default:
          description: Любая неожиданная ошибка
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
    delete:
      summary: Метод удаления организации по идентификатору
      operationId: deleteOrganizationById
      tags:
        - Organizations
      parameters:
        - name: id
          in: path
          required: true
          description: Идентификатор организации
          schema:
            type: string
      responses:
        '200':
          "description": Успешное удаление
          content:
            'application/json': {}
        default:
          description: Любая неожиданная ошибка
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
                
components:
  schemas:
    ResetPassword:
      type: object
      required:
        - newPassword
        - confirmPassword
      properties:
        newPassword:
          type: string
          example: "klimushkin1988"
        confirmPassword:
          type: string
          example: "klimushkin1988"
    SendPincode:
      type: object
      required:
        - email
        - pincode
      properties:
        email:
          type: string
          example: muhammed1942ali@gmail.com
        pincode:
          type: string
          example: 13bbgh
    ForgotPassword:
      type: object
      required:
        - email
      properties:
        email:
          type: string
          example: muhammed1942ali@gmail.com
    LoginUser:
      type: object
      required:
        - email
        - password
      properties:
        email:
          type: string
          example: muhammed1942ali@gmail.com
        password:
          type: string
          example: klimushkin1942
    CreateUser:
      type: object
      required:
        - name
        - email
        - password
      properties:
        name:
          type: string
          example: Артемий
        email:
          type: string
          example: muhammed1942ali@gmail.com
        password:
          type: string
          example: klimushkin1942
    Organization:
      type: object
      required:
        - name
        - description
      properties:
        org_id:
          type: string
          example: 42abcd2b-8b9c-4af9-88f7-0bc180cf74b4
        name:
          description: Название организации
          type: string
          example: Train
        description:
          description: Описание (деятельности) организации
          type: string
    Organizations:
      type: array
      items:
        $ref: "#/components/schemas/Organization"
    Error:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string